// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuws1qO2o4g26_6fmzxxmFg_2mQE63Ai4',
    appId: '1:854211490679:web:54f5e424a2df1582fba772',
    messagingSenderId: '854211490679',
    projectId: 'fir-k-71281',
    authDomain: 'fir-k-71281.firebaseapp.com',
    storageBucket: 'fir-k-71281.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMNMPo2lzszEKzqdGRC6A0xuWKo74Jw2A',
    appId: '1:854211490679:android:1b15dd7fbf4a8a0afba772',
    messagingSenderId: '854211490679',
    projectId: 'fir-k-71281',
    storageBucket: 'fir-k-71281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqWhOB7GRRHzNavEKrFTE2jeHqOr5L1E',
    appId: '1:854211490679:ios:761277266940b916fba772',
    messagingSenderId: '854211490679',
    projectId: 'fir-k-71281',
    storageBucket: 'fir-k-71281.appspot.com',
    iosClientId: '854211490679-g87bffhvottkj3quppc10k651k8crttc.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPqWhOB7GRRHzNavEKrFTE2jeHqOr5L1E',
    appId: '1:854211490679:ios:5ea70fc1be602f5afba772',
    messagingSenderId: '854211490679',
    projectId: 'fir-k-71281',
    storageBucket: 'fir-k-71281.appspot.com',
    iosClientId: '854211490679-rb1rh46b63js8e4dpqqdijpjsc22dla9.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
